### ISSUE TITLE
Broken image URLS in "What is a Process?" section

### ISSUE THREAD

**Issue by datbayev** [happi/theBeamBook#105]
Probably some links are broken, but images are not appearing:

![image](https://user-images.githubusercontent.com/457089/34414284-befcdd62-ebe8-11e7-884b-7d61d4dfd1b3.png)

URL in the book is: https://happi.github.io/images/observer_system.png

**Comment by happi** [comment]
@robertoaloi can you take a look at this?

**Comment by nathanl** [comment]
The images show up at [on the preview page](https://github.com/happi/theBeamBook/blob/master/chapters/processes.asciidoc), but not [on the Github Pages page](https://happi.github.io/theBeamBook/#CH-Processes). If I use Chrome Dev Tools to edit the `src` attribute of one of them there and remove the leading `../`, it works, because the image is at https://happi.github.io/theBeamBook/images/observer_system.png and not at https://happi.github.io/images/observer_system.png.

So I think that references like ` .image::../images/observer_system.png[]` need to have the `../` removed.

**Comment by happi** [comment]
Thanks I have updated the links.
